created html file for results page -sv
ajsherrill2/Project-1-Runtime-Terror pull request #12
Opened 2022-09-10 01:54 UTC by sarahvaci

2022-09-10 15:15 UTC, ajsherrill2 requested changes

2022-09-10 15:15 UTC, ajsherrill2 commented on results.html
> +    <body>
I dont think we need this here as there should only be one body in the html

2022-09-10 15:15 UTC, ajsherrill2 commented on results.html
> +
Can you put the entire nav section inside a header section

2022-09-10 15:15 UTC, ajsherrill2 commented on results.html
> +
can you put this div inside a main section

2022-09-10 15:15 UTC, ajsherrill2 commented on results.html
> +                </div>
make sure there are no blank lines within single divs and that the opening and closing divs are both the same tab distance away from eachother

2022-09-10 21:20 UTC, sarahvaci commented
Changes are updated.

2022-09-11 03:47 UTC, ajsherrill2 approved these changes

2022-09-11 03:47 UTC, merged